### ISSUE TITLE
指定枚举模式后值为None

### ISSUE THREAD

**Issue by sftrwo** [bit4woo/teemo#12]
`parser.add_argument('-b', '--bruteforce', help='Enable the subbrute bruteforce module',nargs='?', default=False)`
跑脚本的时候加上-b参数，args.bruteforce的值为None，导致枚举模式没有启动。不知道是不是我本地环境的问题。
把这个参数的功能从“启用枚举模式”改为“关闭枚举模式”，把default改为True，默认为启用枚举模式会不会更好？

**Comment by bit4woo** [comment]
感谢反馈，bug已修复
