### ISSUE TITLE
关于添加socket代理

### ISSUE THREAD

**Issue by d4wner** [bit4woo/teemo#6]
兄弟的项目不错，但我这边没有http/https代理，只有ss，好像只能走socket吧？
不知道Teemo支不支持socket5。
我那儿没配置代理跑的时候，一直显示：

```
Failed to establish a new connection
```
或者显示：
```
Connection reset by peer
```
开全局代理好像也有点问题，不知道咋回事。

**Comment by bit4woo** [comment]
我用的就是ss ,直接在配置里面写入ss的本地代理地址和端口就可以的

**Comment by bit4woo** [comment]
![image](https://user-images.githubusercontent.com/8793481/35261106-aac27080-0049-11e8-8e59-87d5d2e6a746.png)

**Comment by d4wner** [comment]
ok, 感谢，我还以为非调成sock协议才行。
